# -*- coding: utf-8 -*-
"""capm_selic_day.ipynb

Automatically generated by Colab.


"""

# Install necessary libraries if not already installed


!pip install plotly-express
!pip install yfinance
!pip install pandas  # Usually pre-installed
!pip install numpy   # Usually pre-installed
!pip install statsmodels # Usually pre-installed
!pip install python-bcb

'''



β=1: O ativo tende a se mover em linha com o mercado.
Se o mercado sobe 1%, o ativo tende a subir 1%.

β>1: O ativo tende a ser mais volátil que o mercado.
Se o mercado sobe 1%, o ativo tende a subir mais que 1% (e vice-versa na queda).
 Ex: MGLU3.SA com β≈2.90 é considerado um ativo agressivo.

0<β<1: O ativo tende a ser menos volátil que o mercado.
Se o mercado sobe 1%, o ativo tende a subir menos que 1%.
Ex: BBSE3.SA com β≈0.40 é considerado um ativo defensivo.

β=0: O retorno do ativo não é correlacionado com os retornos do mercado.

β<0: O retorno do ativo tende a se mover na direção oposta ao
mercado (raro para ações individuais).


**Alfa Jensen**:

- Mede o **excesso de retorno total acumulado** sobre o esperado pelo CAPM.

- Captura o efeito composto de todo o período, sem assumir constância.


α>0: Em média, o ativo teve um desempenho diário superior ao que seria previsto pelo seu risco de mercado.
α<0: Em média, o ativo teve um desempenho diário inferior ao que seria previsto pelo seu risco de mercado.
α=0: Em média, o desempenho diário do ativo esteve em linha com o previsto pelo seu risco.



'R²' (R-quadrado)

Definição: O Coeficiente de Determinação (indica a proporção da variância
 nos retornos do ativo que é explicada pela variância nos retornos do mercado (benchmark).

Interpretação:
Varia de 0 a 1 (ou 0% a 100%).

Um R próximo de 1 (ex: 0.80 ou 80%):
 significa que uma grande parte da variação dos retornos do ativo
  é explicada pelos movimentos do mercado. Nesse caso, o Beta é um bom indicador do risco do ativo.

Um R baixo (ex: 0.20 ou 20%) significa que outros fatores
(risco não sistemático ou específico da empresa/setor) têm uma
influência maior nos retornos do ativo, e o Beta explica menos da sua variação.

- R² > 0.7: Forte influência do mercado.

- R² ~ 0.5: Moderada influência (metade do movimento vem do mercado).

- R² < 0.3: Baixa influência.


'p-value Beta' (Valor-p do Beta)

Definição: O valor-p associado ao coeficiente Beta testa a hipótese nula de que o Beta é igual a zero (ou seja, que não há relação linear estatisticamente significativa entre os retornos do ativo e os retornos do mercado).

Interpretação:
Um valor-p baixo (tipicamente < 0.05 ou 5%) indica que podemos rejeitar
 a hipótese nula. Isso significa que o Beta é estatisticamente
 significativo e diferente de zero.

Um valor-p alto ( > 0.05) sugere que o Beta não é estatisticamente significativo, e a relação observada pode ser devida ao acaso.




'Retorno Esperado CAPM'


Interpretação: Representa a taxa de retorno teórica que um investidor
 deveria esperar para ser compensado pelo risco sistemático
 assumido ao investir no ativo.
Exemplo: Para ITSA4.SA, o Retorno Esperado CAPM é 0.3728 (ou 37.28% ao ano).
Este é o retorno que o modelo sugere ser justo para o nível de risco da ITSA4


'Alfa_Jensen' (Alpha de Jensen)

Definição: Mede o desempenho ajustado ao risco de um ativo. É a diferença entre o retorno anualizado real do ativo e o seu retorno esperado anualizado conforme previsto pelo CAPM. Alfa de Jensen = Retorno Anualizado Ativo - Retorno Esperado CAPM
Interpretação:
Alfa de Jensen > 0: O ativo teve um desempenho superior ao que seria justificado pelo seu risco sistemático (Beta). Indica que o ativo (ou o gestor, no caso de um fundo) conseguiu gerar retornos excedentes.
Alfa de Jensen < 0: O ativo teve um desempenho inferior ao esperado para o seu nível de risco.
Alfa de Jensen = 0: O ativo performou exatamente como previsto pelo CAPM.



'''

from bcb import sgs
import pandas as pd
import numpy as np
import plotly_express as px
import yfinance as yf
import statsmodels.api as sm

# Define the date range
start_date = '2025-01-01'
end_date = '2025-12-31'

#Baixando os dados dos ativos
tickers = ['mglu3.sa','sanb3.sa','bbdc3.sa','bbdc4.sa','b3sa3.sa','sapr4.sa','klbn4.sa','itub3.sa','itub4.sa','itsa4.sa','ggbr4.sa','vale3.sa','brap3.sa',
           'bbas3.sa', 'petr4.sa','petr3.sa','taee3.sa','taee4.sa','bbse3.sa','cxse3.sa','alup3.sa','cple3.sa','^BVSP']

def data_set_ativos(tickers, start_date, end_date):

    data = yf.download(tickers, start=start_date, end=end_date)['Close']

    # Organizando os dados em um DataFrame
    df = data.reset_index().melt(id_vars='Date', var_name='Ativo', value_name='Fechamento')


    df = df.astype({'Ativo': 'category', 'Fechamento': 'float64'})
    df = df.assign(Date=pd.to_datetime(df["Date"], errors="coerce"))


    # Pivot the DataFrame to have stocks as columns
    wide_df = df.pivot(index='Date', columns='Ativo', values='Fechamento')

    # Reset index to make 'Date' a column again (optional)
    wide_df = wide_df.reset_index().set_index('Date')
    #wide_df = wide_df

    # Display the result
    return wide_df

wide_df = data_set_ativos(tickers, start_date, end_date)
wide_df.head(3)

# # Define the date range


# Buscar série 11 (SELIC diária)
selic_day = sgs.get({'selic': 11}, start=start_date, end=end_date)
selic_day = selic_day/100

selic_day = selic_day.astype({'selic': 'float64'})

#selic_day = selic_day.assign(Date=pd.to_datetime(selic_day["Date"], errors="coerce"))


# A série já vem como DataFrame do pandas
#print(selic_day.head())
selic_diaria = selic_day[1:]
selic_diaria.head()

dataset = wide_df.copy()

# Remove columns that are entirely NaN (e.g., failed downloads)
dataset = dataset.dropna(axis=1, how='all')

# 1. Calcular retornos-simples
# Specify fill_method=None to suppress future warning
retornos = dataset.pct_change(fill_method=None)

# Merge with selic_diaria. This will automatically align by Date index.
# Rows with no matching index in either DataFrame will be dropped by default (inner join behavior).
retornos = pd.merge(retornos, selic_diaria, left_index=True, right_index=True, how='inner')

# Define benchmark
benchmark = '^BVSP'

# Drop any remaining rows with NaN values in critical columns for CAPM calculation
# Specifically, we need benchmark and Rf_diario (selic) to be non-NaN.
required_cols = [benchmark, 'selic']
retornos = retornos.dropna(subset=required_cols)

# Check if retornos is empty after initial cleaning
if retornos.empty:
    raise ValueError("DataFrame 'retornos' is empty after calculating returns and cleaning. Cannot proceed with CAPM.")

# 2. Definir taxa livre de risco (diária)
Rf_diario = retornos['selic']  # Selic diária

# 3. Calcular Beta para cada ativo
# Ensure that benchmark is in the columns after cleaning
if benchmark not in retornos.columns:
    raise ValueError(f"Benchmark '{benchmark}' not found in returns data after cleaning.")

ativos_total = [item.upper() for item in tickers]
# Filter out benchmark and any tickers that might have been dropped due to all NaNs in `dataset`
ativos_para_capm = [t for t in ativos_total if t != benchmark and t in retornos.columns]
ativos = ativos_para_capm

capm_results = {}
for ativo in ativos:
    # Get the premium for the market and the asset
    X_series = retornos[benchmark] - Rf_diario
    y_series = retornos[ativo] - Rf_diario

    # Combine X and y for this specific asset and drop NaNs for these two series
    # This ensures that OLS only uses valid data points for each asset.
    combined_data = pd.DataFrame({'X': X_series, 'y': y_series}).dropna()

    if combined_data.empty:
        print(f"Skipping CAPM for {ativo}: Not enough valid data points after aligning with benchmark and risk-free rate.")
        continue

    X = combined_data['X']
    y = combined_data['y']

    X = sm.add_constant(X)  # Add alpha (intercept)

    try:
        model = sm.OLS(y, X).fit()
        alpha, beta = model.params

        # Store results, ensure pvalues.iloc[1] exists for beta
        if len(model.pvalues) > 1:
            p_value_beta = model.pvalues.iloc[1]
        else:
            p_value_beta = np.nan # Or handle appropriately if OLS model is too simple

        capm_results[ativo] = {
            'Beta': beta,
            'Alpha': alpha,
            'R²': model.rsquared,
            'p-value Beta': p_value_beta,
        }
    except Exception as e:
        print(f"Error calculating CAPM for {ativo}: {e}")
        continue

# DataFrame de resultados
resultados_capm = pd.DataFrame(capm_results).T

if resultados_capm.empty:
    raise ValueError("No CAPM results were successfully calculated. 'resultados_capm' is empty.")


# 5. Calcular retorno esperado anualizado (CAPM)

# Ensure retornos[benchmark] and Rf_diario are not empty for these calculations
if retornos[benchmark].empty or Rf_diario.empty:
    E_Rm = 0
    Rf_anualizada = 0
else:
    E_Rm = (1 + retornos[benchmark]).prod() ** (252 / len(retornos)) - 1
    Rf_anualizada = (1 + Rf_diario).prod() ** (252 / len(Rf_diario)) - 1

E_Rm_minus_Rf = E_Rm - Rf_anualizada  # Prêmio de mercado anualizado

# This part needs to be careful if Beta is NaN due to empty capm_results
if not resultados_capm.empty and 'Beta' in resultados_capm.columns:
    resultados_capm['Retorno Esperado CAPM'] = (
        Rf_anualizada + resultados_capm['Beta'] * E_Rm_minus_Rf
    )
else:
    resultados_capm['Retorno Esperado CAPM'] = np.nan # Assign NaN if no betas

# Supondo que 'ativos' é a lista de tickers dos ativos (excluindo o benchmark)
# e que essas são as colunas em 'retornos' e índices em 'resultados_capm'
retornos_ativos_anualizados = {}
for ativo_ticker in resultados_capm.index: # ou use a lista 'ativos' definida anteriormente
    ret_ativo_anual = (1 + retornos[ativo_ticker]).prod() ** (252 / len(retornos[ativo_ticker])) - 1
    retornos_ativos_anualizados[ativo_ticker] = ret_ativo_anual

# Converta para uma Série alinhada com resultados_capm
retornos_ativos_anualizados_series = pd.Series(retornos_ativos_anualizados)

resultados_capm['Retorno Anualizado Ativo'] = retornos_ativos_anualizados_series
resultados_capm['Alfa_Jensen'] = resultados_capm['Retorno Anualizado Ativo'] - resultados_capm['Retorno Esperado CAPM']

#resultados_capm['alpha_linear'] = resultados_capm['Alpha'] * 252 # alpha aproximado
#resultados_capm


resultados_capm_sorted = resultados_capm.sort_values(by='Alfa_Jensen', ascending=False)
resultados_capm_sorted

df_capm = resultados_capm.copy()


if df_capm.empty or 'p-value Beta' not in df_capm.columns:
    if df_capm.empty and 'p-value Beta' not in capm_results: # Checa se a chave original também não existe
         print("A chave 'p-value Beta' não foi encontrada no dicionário original.")
    elif 'p-value Beta' not in df_capm.columns:
        print("A coluna 'p-value Beta' não foi encontrada no DataFrame.")
else:
    significance_level = 0.05
    all_significant = True
    non_significant_assets_df = []

    # Iterar sobre a coluna 'p-value Beta' do DataFrame
    # .items() em uma Series do Pandas retorna pares de (índice, valor)
    for asset_ticker, p_value in df_capm['p-value Beta'].items():
        if pd.isna(p_value): # Checa se o valor é NaN (Not a Number)
            print(f"Aviso: p-valor ausente (NaN) para o ativo {asset_ticker}. Ignorando.")
            continue # Pula para o próximo ativo

        if p_value > significance_level:
            all_significant = False
            non_significant_assets_df.append({'ativo': asset_ticker, 'p_value_beta': p_value})

    if all_significant:
        # Verifica se a lista non_significant_assets_df está realmente vazia,
        # pois um p-valor NaN pode ter feito com que não fosse adicionado,
        # mas não queremos dizer que "todos são significativos" se houve dados ausentes.
        # No entanto, a lógica atual já cuida disso, pois all_significant só se mantém True
        # se todos os p-valores válidos forem <= significance_level.
        print("todos são significativos.")
    else:
        print("\nUm ou mais Betas não são estatisticamente significativos (p-valor > 0.05):")
        for item in non_significant_assets_df:
            print(f"Ativo: {item['ativo']}, p-value Beta: {item['p_value_beta']}")



###capm potifólio
lista_uniforme = [1/len(resultados_capm)] * len(resultados_capm)
product = np.multiply(np.array(lista_uniforme),np.array(resultados_capm['Retorno Esperado CAPM'])   )
capm_portfolio = np.sum(product)
capm_portfolio
