# -*- coding: utf-8 -*-
"""dividend yield.ipynb

Automatically generated by Colab.


"""

!pip install playwright beautifulsoup4 nest_asyncio yfinance pandas numpy
!playwright install # This installs the browser binaries for Playwright
!playwright install-deps # This installs system dependencies for Playwright

import asyncio
import numpy as np
import pandas as pd
from playwright.async_api import async_playwright
from bs4 import BeautifulSoup
import nest_asyncio
import yfinance as yf

nest_asyncio.apply()  # Apply the patch to allow nested event loops

async def fundamentus_dataframe(papeis):
    """
    Extracts fundamentus data for a list of paper codes and returns a combined DataFrame.

    Args:
        papeis (list): A list of paper codes (e.g., ["klbn4", "petr4"]).

    Returns:
        pd.DataFrame: A combined DataFrame containing fundamentus data for the provided papers,
                      or an empty DataFrame if no data was extracted.
    """

    all_dfs = []

    async with async_playwright() as p:
        browser = await p.chromium.launch(headless=True)

        for papel in papeis:
            url = f"https://fundamentus.com.br/proventos.php?papel={papel}"
            page = await browser.new_page()

            try:
                await page.goto(url, timeout=60000)
                await page.wait_for_selector("#resultado", timeout=60000)
                html = await page.content()

                soup = BeautifulSoup(html, "html.parser")
                table = soup.find("table", {"id": "resultado"})

                if table:
                    header = [th.text.strip() for th in table.find("thead").find_all("th")]
                    data = []
                    for row in table.find("tbody").find_all("tr"):
                        cols = row.find_all("td")
                        data.append([col.text.strip() for col in cols])

                    df = pd.DataFrame(data, columns=header)
                    df['Papel'] = papel
                    all_dfs.append(df)
                    print(f"Dados de {papel} extraídos.")
                else:
                    print(f"Tabela #resultado não encontrada para {papel}")

            except Exception as e:
                print(f"Erro ao processar {papel}: {e}")
            finally:
                await page.close()  # Ensure the page is closed in all cases

        await browser.close()

    if all_dfs:
        final_df = pd.concat(all_dfs, ignore_index=True)
        #print("\nDataFrame Combinado:\n")
        #print(final_df)
        return final_df
    else:
        print("Nenhum dado foi extraído.")
        return pd.DataFrame()

#papeis=['vale3']
#start_date='2025-01-01'
#end_date ='2025-06-04'

def dividendos(papeis, start_date , end_date  ):

    final_dataframe = asyncio.run(fundamentus_dataframe(papeis))
    final_dataframe.rename(columns = {"Data": "Data", "Valor": "Valor" , "Tipo": "Tipo", "Data de Pagamento": "Data_de_Pagamento",
                                    "Por quantas ações" : "Por_Quantos_Ativos", 'Papel':"Papel" }, inplace = True )

    for coluna in final_dataframe.columns:
        final_dataframe[coluna] = final_dataframe[coluna].replace('-', np.nan)

    final_dataframe['Valor'] = final_dataframe['Valor'].str.replace(',', '.')

    final_dataframe = final_dataframe.astype({
    'Papel': 'category',
    'Tipo': 'category',
    'Por_Quantos_Ativos': 'int64',
    'Valor': 'float64'
    })

    # Converter datas especificando o formato e dayfirst=True
    final_dataframe = final_dataframe.assign(
    Data_de_Pagamento=pd.to_datetime(
        final_dataframe["Data_de_Pagamento"],
        format='%d/%m/%Y',
        dayfirst=True,
        errors='coerce'
    )
    )

    final_dataframe = final_dataframe.assign(
    Data=pd.to_datetime(
        final_dataframe["Data"],
        format='%d/%m/%Y',
        dayfirst=True,
        errors='coerce'
    )
    )

    final_dataframe['Papel'] = final_dataframe['Papel'].str.upper() + '.SA'
    final_dataframe = final_dataframe.set_index('Data')
    final_dataframe_sum = final_dataframe.loc[(final_dataframe['Data_de_Pagamento'] >= start_date ) &  (final_dataframe['Data_de_Pagamento'] <= end_date )].groupby('Papel', as_index=False)['Valor'].sum().sort_index()

    final_dataframe_sum.rename(columns = {"Papel": "Papel", "Valor": "SUM" }, inplace = True )




    # Baixando os dados dos ativos
    tickers = final_dataframe['Papel'].unique().tolist()

    data = yf.download(tickers, start=start_date, end=end_date)['Close']

    # Organizando os dados em um DataFrame
    df = data.reset_index().melt(id_vars='Date', var_name='Ativo', value_name='Fechamento')


    df = df.astype({'Ativo': 'category', 'Fechamento': 'float64'})
    df = df.assign(Date=pd.to_datetime(df["Date"], errors="coerce"))


    media_ajustada_2024 = df.groupby('Ativo', observed=False)['Fechamento'].mean().reset_index()
    media_ajustada_2024.columns = ['Papel', 'MEAN']

    last_value = df.groupby('Ativo', observed=False).tail(1)[['Ativo', 'Fechamento']]
    last_value.columns = ['Papel', 'Last_Value']


    resultado_2024 = pd.merge(final_dataframe_sum, media_ajustada_2024, on='Papel')
    resultado_2024 = pd.merge(resultado_2024, last_value, on='Papel')



    resultado_2024['YIELD MEAN'] = (  (resultado_2024['SUM'] * 0.85)  /  resultado_2024['MEAN']  )*100
    resultado_2024['YIELD_LAST'] = (  (resultado_2024['SUM'] * 0.85)  /  resultado_2024['Last_Value']  )*100


    resultado_sorted_2024 = resultado_2024.sort_values(by='YIELD_LAST', ascending=False)

    return resultado_sorted_2024

papeis=['vale3','bbdc3','bbas3','itub4','itsa4','itub3','petr3','petr4','bbse3','pssa3','wege3','elet3']
start_date='2025-01-01'
end_date ='2026-01-01'

resultado = dividendos(papeis, start_date, end_date)
resultado
